# Test with different Racket versions
# More details: https://github.com/greghendershott/travis-racket
language: c

sudo: false

services:
  - xvfb

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=7.6
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=HEADCS
    - RACKET_VERSION=RELEASE
    - RACKET_VERSION=RELEASECS

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script:
  - raco test --table -Q sotoseattle/sandbox/game_of_life/gol.rkt

notifications:
  email:
    on_success: never
    on_failure: always

